goog.provide('webly.app.routes');
webly.app.routes.webly_routes_api = new cljs.core.PersistentArrayMap(null, 4, ["config",new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"get","get",1683182755),new cljs.core.Keyword("webly","config","webly/config",881771848)], null),"oauth2/",cljs.core.PersistentArrayMap.createAsIfByAssoc([new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, ["start/",new cljs.core.Keyword(null,"provider","provider",-302056900)], null),new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"get","get",1683182755),new cljs.core.Keyword("oauth2","start","oauth2/start",768329080)], null),"token",new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"get","get",1683182755),new cljs.core.Keyword("oauth2","token","oauth2/token",1925404990)], null),"save-token",new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"post","post",269697687),new cljs.core.Keyword("oauth2","save-token","oauth2/save-token",-1644568672)], null)]),"token",new cljs.core.Keyword("ws","token","ws/token",-1211458851),"chsk",new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"get","get",1683182755),new cljs.core.Keyword("ws","chsk-get","ws/chsk-get",-350909948),new cljs.core.Keyword(null,"post","post",269697687),new cljs.core.Keyword("ws","chsk-post","ws/chsk-post",1101538704)], null)], null);
webly.app.routes.webly_routes_app = cljs.core.PersistentArrayMap.EMPTY;
webly.app.routes.make_routes_frontend = (function webly$app$routes$make_routes_frontend(user_routes_app){
return new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, ["/",cljs.core.merge.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([webly.app.routes.webly_routes_app,user_routes_app], 0))], null);
});
webly.app.routes.make_routes_backend = (function webly$app$routes$make_routes_backend(user_routes_app,user_routes_api){
var api_routes = cljs.core.merge.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([webly.app.routes.webly_routes_api,user_routes_api], 0));
return new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, ["/",cljs.core.PersistentArrayMap.createAsIfByAssoc(["api/",api_routes,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, ["oauth2/redirect/",new cljs.core.Keyword(null,"provider","provider",-302056900)], null),new cljs.core.Keyword("oauth2","redirect","oauth2/redirect",1061581509),new cljs.core.PersistentHashSet(null, new cljs.core.PersistentArrayMap(null, 2, ["bundel",null,"r",null], null), null),webly.web.resources.file_handler_bundel,new cljs.core.PersistentHashSet(null, new cljs.core.PersistentArrayMap(null, 2, ["r",null,"node",null], null), null),webly.web.resources.file_handler_nodejs,new cljs.core.PersistentHashSet(null, new cljs.core.PersistentArrayMap(null, 2, ["jarres",null,"r",null], null), null),webly.web.resources.resource_handler,"code/",webly.web.resources.file_handler_code])], null);
});

//# sourceMappingURL=webly.app.routes.js.map
